// Generated by Haxe 4.3.0
(function ($global) { "use strict";
var BadNums = function() { };
BadNums.main = function() {
	console.log("BadNums.hx:5:","Hello world!");
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
BadNums.main();
})({});
