// Generated by Haxe 4.3.0
(function ($global) { "use strict";
var Main = function() { };
Main.generateRandom = function(len) {
	if(len == null) {
		len = 100;
	}
	var rVec = new Array(len);
	var _g = 0;
	var _g1 = len;
	while(_g < _g1) {
		var v = _g++;
		rVec[v] = Math.round(Math.random() * 100000);
	}
	return rVec;
};
Main.main = function() {
	var i = 0;
	var rVec = Main.generateRandom(Main.totalLen);
	console.log("Main.hx:16:",rVec);
	while(i < Main.totalLen - 1) {
		if(rVec[i] > rVec[i + 1]) {
			var tVar = rVec[i];
			rVec[i] = rVec[i + 1];
			rVec[i + 1] = tVar;
			--i;
		} else {
			++i;
		}
		if(i < 0) {
			i = 0;
		}
	}
	console.log("Main.hx:28:",rVec);
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
Main.totalLen = 10;
Main.main();
})({});
